android_build_config(
  name = 'build_config',
  package = 'com.facebook.shimmer',
)

android_resource(
  name = 'res',
  res = 'src/main/res',
  package = 'com.facebook.shimmer',
  visibility = ['PUBLIC'],
)

android_library(
  name = 'src',
  srcs = glob(['src/main/java/**/*.java']),
  deps = [':res', ':build_config'],
  visibility = ['PUBLIC'],
)

project_config(
  src_target = '//shimmer-android:src',
  src_roots = ['src/main/java'],
)
